name: Called Workflow

on:
  workflow_run:
    workflows: ["Every Push Workflow", "Manual Workflow"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Print Calling Workflow
      run: echo "Calling Workflow: ${{ github.event.workflow }} from repository ${{ github.event.repository }}"
# ? Nested mappings are not allowed in compact mappings at line 15, column 12:

