name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set Timestamp Environment Variable
      run: |
        echo "env_workflow_manual_timestamp=$(date +'%Y-%m-%d--%H-%M-%S--%N')" >> $GITHUB_ENV
